### ISSUE TITLE
Provide model labels in models descriptions and links to original sources

### ISSUE THREAD

**Issue by dvrogozh** [openvinotoolkit/open_model_zoo#1559]
Some models like https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/resnet-50, https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/ssd_mobilenet_v2_coco, etc. output object IDs for which human readable label lists exist. However these lists are not provided along with the model and there are no links to original lists or any instruction how to get them. Workaround might be to search in demo examples like here https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/classification_demo, but this is not straight forward way if you don't look in the demos at the first place.

Can you, please, consider enhancing model descriptions with labels and links to original sources?

**Comment by eizamaliev** [comment]
Thanks for feedback!
It would be appear in one of the further releases.

**Comment by florian-fischer-swarm** [comment]
+1
Also, for the Intel models, I wonder if it is possible to share more information about the training or the used datasets (or maybe even source)?

**Comment by vladimir-dudnik** [comment]
@dvrogozh a folder `data/dataset_classes` created where we keep label files for public models, see PR #1996 "Create data folder for dataset definitions and labels" for details

@florian-fischer-swarm for Intel models which provided a training pipeline through [OpenVINO Training Extensions](https://github.com/openvinotoolkit/training_extensions) we added a reference in corresponding models descriptions. See PR #2397 "add OpenVINO Training Extensions links" for details.

Let me know if you have additional questions, otherwise I'll close this ticket.

**Comment by vladimir-dudnik** [comment]
answers provided, so I'll close this. Feel free to reopen if you have additional questions
