### ISSUE TITLE
Unable to run road-segmentation-adas-0001

### ISSUE THREAD

**Issue by Pulkit0810** [openvinotoolkit/open_model_zoo#1740]
Hi Team,

I am using the road-segmentation model, where I am inferencing the roads and traffic, but I am getting the below erros:

> Traceback (most recent call last):
>   File "segmentation_demo.py", line 148, in <module>
>     sys.exit(main() or 0)
>   File "segmentation_demo.py", line 88, in main
>     assert len(net.input_info) == 1, "Sample supports only single input topologies"
> AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'input_info'

> **Running command:**
> For Video:
 python3 segmentation_demo.py -i traffic.mp4 -m road-segmentation-adas-0001.xml
> For Image:
 python3 segmentation_demo.py -i test_traffic.PNG -m road-segmentation-adas-0001.xml

I had tried this demo with FP16 and FP32, but getting the same above issue while running the demo.
Please correct me how i can proceed further.

Thanks 
Pulkit

**Comment by eaidova** [comment]
Hi @Pulkit0810 
`input_info` was introduced in openvino 2020.4 if I right remember.
if you see such error, it means that version of demo, which you try to use, is not compatible with openvino version which you have.
Please update openvino package or use demo which distributed inside your openvino version (<openvino_install>/deployment_tools/opn_model_zoo/demos)

**Comment by Pulkit0810** [comment]
> Hi @Pulkit0810
> `input_info` was introduced in openvino 2020.4 if I right remember.
> if you see such error, it means that version of demo, which you try to use, is not compatible with openvino version which you have.
> Please update openvino package or use demo which distributed inside your openvino version (<openvino_install>/deployment_tools/opn_model_zoo/demos)

Thankyou so much @eaidova 
We had updated our openvino and now we are successufully able to run this demo and found the results.

Actually, we are trying to generate the pipeline for road segmentation (gstreamer + openvino)
And  I found, Instead of returning bounding boxes, semantic segmentation models return a "painted" version of the input image, where the "color" of each pixel represents a certain class.

Is there any solution how we can go forward with gstreamer + openvino and How we can implement own $POST_PROCESSOR?
**Below is our pipeline which we are making**
```
gst-launch-1.0 filesrc=$VIDEO_SAMPLE ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! \
gvainference model=$ROAD_SEGMENTATION_MODEL ! queue ! \
gvapython module=$POST_PROCESSOR ! \
videoconvert ! xvimagesink sync=false"
```

Thanks

**Comment by eaidova** [comment]
@Pulkit0810 semantic segmentation is the task of partitioning a digital image into multiple segments (sets of pixels) based on some characteristics.. Generally, it represents like classification but for every pixel (each pixel of image contains a number of class that it belongs). It is impossible to get boxes based on this approach, because semantic segmentation makes meaningful only semantic, not instance of object, it can group several objects to one semantic area if they located close (e.g. if you have image with parking lot, where 2 cars are parked close to each other, semantic segmentation can return one area of label of car and you can not say which pixel belongs to first cars and which to second). So it will not be suitable if you need boxes.

you can find info about model output in its [description](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/road-segmentation-adas-0001/description/road-segmentation-adas-0001.md#outputs)
road segmentation model returns probability across of 4 classes for image in 512x896 resolution. 
For getting certain label of pixel, you need to get class with max probability (argmax by dimension with classes), then you need encode classes in colors (otherwise you get very dark result) according your defined color coding.

I am sorry, I am not very familiar with dlstreamer interface, probably @dsmertin can give you more practical advice.

**Comment by Pulkit0810** [comment]
> @Pulkit0810 semantic segmentation is the task of partitioning a digital image into multiple segments (sets of pixels) based on some characteristics.. Generally, it represents like classification but for every pixel (each pixel of image contains a index of class that it belongs). It is impossible to get boxes based on this approach, because semantic segmentation makes meaningful only semantic, not instance of object, it can group several objects to one semantic area if they located close (e.g. if you have image with parking lot, where 2 cars are parked close to each other, semantic segmentation can return one area of label of car and you can not say which pixel belongs to first cars and which to second). So it will not be suitable if you need boxes.
> 
> you can find info about model output in its [description](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/road-segmentation-adas-0001/description/road-segmentation-adas-0001.md#outputs)
> road segmentation model returns probability across of 4 classes for image in 512x896 resolution.
> For getting certain label of pixel, you need to get class with max probability (argmax by dimension with classes), then you need encode classes in colors (otherwise you get very dark result) according your defined color coding.
> 
> I am sorry, I am not very familiar with dlstreamer interface, probably @dsmertin can give you more practical advice.

Thankyou, thankyou @eaidova for all.

**Comment by vladimir-dudnik** [comment]
@Pulkit0810 do you have additional questions or we can close this issue?

**Comment by Pulkit0810** [comment]
Thanks @vladimir-dudnik 
yes we can close this issue.
