### ISSUE TITLE
object detection demo yolov3 async

### ISSUE THREAD

**Issue by Eduardo-az** [openvinotoolkit/open_model_zoo#1751]
I've tried use my neuronal network after converting it with Open-VINO toolkit but when I ran the script I get an error. 
Can you help me? 
![image](https://user-images.githubusercontent.com/56844523/98332762-e3c01700-1fc4-11eb-8ae0-2798c3980ba4.png)

**Comment by vladimir-dudnik** [comment]
@Eduardo-az it seems your network is architecturally different from variant of YOLO this sample was designed to work with. You need to adopt model postprocessing implementation to your model specific.

**Comment by eizamaliev** [comment]
@Eduardo-az how did you convert your model? Did you use `--transformation_config` option?

**Comment by Eduardo-az** [comment]
Firts I converted yolov3 trained weights to tensorflow frozen model:

python3 convert_weights_pb.py --class_names classes.names --data_format NHWC --weights_file yolov3_ckpt_49.pth

Next I converted the frozen model file into IR files using OpenVINO inference engine, I only used these **flags**:

python3 mo_tf.py **--input_model** /path/to/yolo_v3.pb -**-tensorflow_use_custom_operations_config** /extensions/front/tf/yolo_v3.json **--batch** 1

I'm only working with one class. 

I don't use --transformation_config option.

**Comment by eizamaliev** [comment]
1. Since you trained yolo with single class (don't you?) you should modify `yolo_v3.json` file by specifying class number in `classes` field. May be fix anchors.
1. You should specify input shape `--input_shape [1,416,416,3]` (or whatever you got)
1. Try `--transformations_config` option instead of `--tensorflow_use_custom_operations_config`

Also, could specify which version of OpenVINO is used

**Comment by vladimir-dudnik** [comment]
@Eduardo-az do you have additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
