### ISSUE TITLE
PRNet (and maybe other models) don't appear on public model zoo.

### ISSUE THREAD

**Issue by gustavofuhr** [openvinotoolkit/open_model_zoo#1777]
Reading the release notes for the 2020.4 version:
https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/NEW-RELEASE-OpenVINO-toolkit-2020-4/td-p/1192267

there is new support for these models:
> Support for additional public models, which includes:
> Original models: DeepSpeech, GPT-2, 3D U-Net and PRNet models
> Low precision (that is, int8) models: MTCNN, 3D U-Net, BERT model, PRNet 3D, DCSCN, and support for quantization of cascaded models for improved performance when converting models into a pipeline

Reading that, it was my understanding that these models will be available in the model zoo, using downloader.py and listed in https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/index.md

That was not the case for PRNet (I didn't check the others). What's up with that? Thanks

**Comment by gustavofuhr** [comment]
This PR seems associated: https://github.com/openvinotoolkit/open_model_zoo/pull/1055

**Comment by eaidova** [comment]
@gustavofuhr models treated as supported if it can be successfully converted and inferenced by openvino, they may be not included by OMZ due to some reasons, for example:
* have non-permissive license (Note that we accept models under permissive licenses, such as MIT, Apache 2.0, and BSD-3-Clause.)
* no pretained model publicly available in downloadable format
* required additional hard preconversion steps
and many other.

Regarding PRNet, unfortunately, it was not approved for publication as part of OMZ due to legal reasons (the answer why provided in the PR, see my [comment](https://github.com/openvinotoolkit/open_model_zoo/pull/1055#issuecomment-633548641)), but it does not mean that you can not download it from original source and try to run with openvino.
My PR just speak that it is possible to check model accuracy using Accuracy Checker tool (it can be seen from PR  prefix AC) and openvino.

**Comment by gustavofuhr** [comment]
Got it, thanks @eaidova.

I was just wondering that, in this case it should be useful to have a link to the implementation that was successfully converted. In this specific case of PRNet I'm considering this one: https://github.com/FengYen-Chang/PRNetOpenVINO
