### ISSUE TITLE
[Urgent]Value error in object_detection_demo_yolov3_async.py 

### ISSUE THREAD

**Issue by NSVR57** [openvinotoolkit/open_model_zoo#1849]
receiving the following error when i am trying to execute object_detection_demo_yolov3_async.py .
My command:

`!python3 object_detection_demo_yolov3_async.py -m '/home/u50737/model/FP16/yolov3New.xml' -i '/home/u50737/Object_detection/cars_1900.mp4'`

```
[ INFO ] Creating Inference Engine...
[ INFO ] Loading network
[ INFO ] Preparing inputs
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key
To switch between min_latency/user_specified modes, press TAB key in the output window
object_detection_demo_yolov3_async.py:228: DeprecationWarning: 'layers' property of IENetwork class is deprecated. For iteration over network please use get_ops()/get_ordered_ops() methods from nGraph Python API
  out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 490, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 380, in main
    args.keep_aspect_ratio)
  File "object_detection_demo_yolov3_async.py", line 231, in get_objects
    prob_threshold, is_proportional)
  File "object_detection_demo_yolov3_async.py", line 143, in parse_yolo_region
    _, _, out_blob_h, out_blob_w = predictions.shape
ValueError: too many values to unpack (expected 4)
```

**Comment by vladimir-dudnik** [comment]
@NSVR57 you may see the list of models supported by each demo in [models.lst](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_yolov3_async/models.lst) file and I do not see yolov3New listed there

**Comment by NSVR57** [comment]
its Yolov3 trained on pytorch and converted to ONNX.  is thins wont work ?

**Comment by vladimir-dudnik** [comment]
@NSVR57 it may work or may not, The fact is that the list of models what we have validated demo on is shown in [models.lst](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_yolov3_async/models.lst). If demo does not work with your model, you may need to dive into details to find how your model differ from models we support in this demo and once you find what and where the difference is you probably will see what should be changed in application (most probably your model requires different post processing in order to extract yolo detection results).

**Comment by eaidova** [comment]
@NSVR57 it depends from do you have included postprocessing (bbox decoding and nms) in your model or not. 
If the output format is the same like in caffe and tf (YoloRegion layer is the final), then demo should work, otherwise not.
As I know in onnx model version is output has different format, it is the reason wht you see the error and our demo is not suitable.
We will be glad to review  your changes if you wish to contribute the onnx yolo v3 support in the demo :)

**Comment by NSVR57** [comment]
bbox decoding and nms is not included in the model. i am still trying to figure it out the post-processing for my case

**Comment by eizamaliev** [comment]
@NSVR57 could you print output layers parameters from IR?

**Comment by NSVR57** [comment]
Hi @eizamaliev 

--transformation_configs is not for mo.py or mo_onnx.py. getting below error. 
```

usage: mo.py [options]
mo.py: error: unrecognized arguments: --transformation_configs /opt/intel/openvino_2020.3.341/deployment_tools/model_optimizer/extensions/front/tf/yolo_v3.json
```

**Comment by NSVR57** [comment]
@eizamaliev 
I think that Json is for tensorflow. but my model in onnx trained on pytorch

**Comment by vladimir-dudnik** [comment]
@NSVR57 do you have any additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
