### ISSUE TITLE
Not able to run human pose estimation demo human_pose_estimation_demo.py

### ISSUE THREAD

**Issue by kunalgaurav18** [openvinotoolkit/open_model_zoo#2257]
Hi 

I completed the setup of openvino on windows 10. 
I am running openvino version 2020.3 and python version 3.6.

I downloaded the python file(human_pose_estimation_demo.py) and model.lst(present in the same folder) file from github.

Now when I run the following command:

`python human_pose_estimation_demo.py -h`

I get following error:

```
Traceback (most recent call last):
  File "human_pose_estimation_demo.py", line 29, in <module>
    import models
ModuleNotFoundError: No module named 'models'
```

Cannot figure out what am I missing here.
Could someone help please?

Later I am planning to run this on Inter NCS2.

**Comment by vladimir-dudnik** [comment]
Hi @kunalgaurav18,

it seems you installed some old version of OpenVINO 2020.3. We are glad to inform you that the latest version of OpenVINO 2021.3 was just released a few days ago, would not you mind to try the latest and greatest version?

Regarding the issue you met, the problem is that files you downloaded from Open Model Zoo github are correspond to new version of OpenVINO, while you have installed old, 2020.3 version. Moreover, you actually do not need to download Open Model Zoo from github, when you have OpenVINO insatlled. Open Model Zoo is distributed as a part of OpenVINO package, just take look at "C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\deployment_tools\open_model_zoo" folder and you will find Open Model Zoo, corresponding to your OpenVINO version.

The following human pose estimation models tested to work on MyriadX stick with OpenVINO 2021.3
human-pose-estimation-0001
human-pose-estimation-0005
human-pose-estimation-0006
human-pose-estimation-0007

**Comment by kunalgaurav18** [comment]
Thank you so much @vladimir-dudnik  for the quick help.

I have now installed OpenVINO 2021.3. The issue was really with the version of OpenVINO.
I am now able to run the model on CPU, GPU and MYRIAD.

Thank you.
