### ISSUE TITLE
Where is the new link of the OpenVINO-Toolkit Model-Zoo

### ISSUE THREAD

**Issue by Bahramudin** [openvinotoolkit/open_model_zoo#2314]
Before I found the models [here](https://download.01.org/opencv/2021/openvinotoolkit/), but now OpenVINO Toolkit already updated to 2021.3, but I cannot see the update in the mentioned link.
So now where I can find the model-zoo?
Thanks!

**Comment by vladimir-dudnik** [comment]
Hi @Bahramudin we do recommend to use Open Model Zoo [Model Downloader](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/README.md) instead of access models by direct link. Note, Model Downloader from particular OpenVINO release will download models which where built and validated for this release. For your information, Model Downloader use configuration files, located at each model subfolder, for example, for age-gender-recognition-retail-0013: [`model.yml`](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/age-gender-recognition-retail-0013/model.yml). You may examine this file for model of your interest, to see exact link for model downloading.

**Comment by Bahramudin** [comment]
Thanks, @vladimir-dudnik! I got my answer.

**Comment by vladimir-dudnik** [comment]
ok, then I'll close this
