### ISSUE TITLE
Error LNK1104 Cannot open the file "ngraph::ngraph.lib" 

### ISSUE THREAD

**Issue by su26225** [openvinotoolkit/open_model_zoo#2626]
In the Cmakelist.txt of multi_channel_object_detection_demo_yolov3, there is such a sentence 
`target_link_libraries(${TARGET_NAME} PRIVATE
    ${InferenceEngine_LIBRARIES} gflags ${OpenCV_LIBRARIES} ngraph::ngraph monitors multi_channel_common)

if(COMMAND add_cpplint_target)
    add_cpplint_target(${TARGET_NAME}_cpplint FOR_TARGETS ${TARGET_NAME})`

I don't know what the "ngraph::ngraph.lib" mean,especially the symbol "::" . OK , I can't find the file when I run the demo of  multi_channel_object_detection_demo_yolov3,what can I do to solve it ? Thanks .

**Comment by vladimir-dudnik** [comment]
@su26225 you probably build sample with OpenVINO for RaspberryPi package, is not it? The nGraph is one of the OpenVINO runtime components, intended to transform network model graph to graph of OpenVINO layers (mostly it is used by model optimizer and usually not required at application runtime. But there are few cases, when application may need to extract additional information about network layers and its parameters, namely, in multi_channel_object_detection_demo_yolov3 it is used to extract additional yolo parameters which otherwise not accessible through inference engine. On RaspberryPi nGraph library is not included into install package, so you may need to build it on your side, according to OpenVINO instructions, available on github.

**Comment by su26225** [comment]
> @su26225  so you may need to build it on your side, according to OpenVINO instructions, available on github.

Thanks for your reply , but I don't find the tutorial to build it on github  ,where can I find it ?
In addition ,How should this file be named? A file with this character "::" cannot exist .

**Comment by vladimir-dudnik** [comment]
@su26225 There is a link to [Build OpenVINO Inference Engine](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode) instruction on OpenVINO Wiki
ngraph::ngraph is not a file name, it is [alias](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#imported-targets) name of CMake target.

**Comment by vladimir-dudnik** [comment]
@su26225 do you have additional questions?

**Comment by vladimir-dudnik** [comment]
closing as answered
