### ISSUE TITLE
Support python 3.10

### ISSUE THREAD

**Issue by skaldesh** [openvinotoolkit/open_model_zoo#3043]
I followed the install guide on https://pypi.org/project/openvino-dev/  
When running the command `python -m pip install openvino-dev[caffe,onnx,tensorflow2,pytorch,mxnet]==2021.4.2` this error occurred:  
```
Collecting openvino-dev[caffe,mxnet,onnx,pytorch,tensorflow2]==2021.4.2
  Using cached openvino_dev-2021.4.2-3976-py3-none-any.whl (6.2 MB)
Collecting pandas~=1.1.5
  Using cached pandas-1.1.5.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scikit-image>=0.17.2
  Using cached scikit_image-0.19.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.8 MB)
Collecting opencv-python==4.5.*
  Using cached opencv_python-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.4 MB)
Collecting tqdm>=4.54.1
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting nltk>=3.5
  Using cached nltk-3.6.7-py3-none-any.whl (1.5 MB)
Collecting sentencepiece>=0.1.95
  Using cached sentencepiece-0.1.96-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Collecting hyperopt~=0.1.2
  Using cached hyperopt-0.1.2-py3-none-any.whl (115 kB)
Collecting editdistance>=0.5.3
  Using cached editdistance-0.6.0.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement fast-ctc-decode>=0.2.5 (from openvino-dev[caffe,mxnet,onnx,pytorch,tensorflow2]) (from versions: none)
ERROR: No matching distribution found for fast-ctc-decode>=0.2.5
```
I am using a virtual environment, as suggested in the install guide. Does somebody know why this fails?

**Comment by eaidova** [comment]
@skaldesh which python version do you use?

**Comment by skaldesh** [comment]
`python 3.10.1`

**Comment by eaidova** [comment]
@skaldesh unfortunatly, this version is not supported on our side yet.. some thirdparty components can not be found for this python version on pypi (ctc-decode is available only for 3.9 now as I can see https://pypi.org/project/fast-ctc-decode/0.3.0/#files, you can try to install it manually from repo to resolve the current issue, but after that, you will get another issue because the key dependency of openvino-dev is openvino 2021.4.2, which is also available only for python3.9 and below)

My recommendation is downgrade python version for now...
@slyubimt do you have plans to support python3.10 for openvino and openvino-dev for pypi distribution?

**Comment by skaldesh** [comment]
Ah understood, thank you! I'll change the title then...

**Comment by eaidova** [comment]
openvino 2022.3 release introduced python 3.10 support, please try
