### ISSUE TITLE
Builde demos successfully.But video connection refused!!!

### ISSUE THREAD

**Issue by xiuxiusen** [openvinotoolkit/open_model_zoo#3460]
Operating system:Ubuntu mate 20.04
I have successfully build open_model_zoo on my RPi 4B.And the directory omz_demos_build occurs.
I use the intel realsense D435i and NCS2.
I follwoed this link https://docs.openvino.ai/latest/omz_demos_human_pose_estimation_demo_cpp.html. Then I open ~/omz_demos_build/aarch64/Release in the Terminal.
I run the commend ./human_pose_estimation_demo -i /dev/video -m ~/intel/human-pose-estimation-0001/FP16/human-pose-estimation-0001.xml -d MYRIAD
And it says connect:Connection refused.
Does anyone meet the same question?
Thanks for any help what so ever! More than happy to provide further info if required.

**Comment by vladimir-dudnik** [comment]
@xiuxiusen have you tried this demo with input from video or image file instead of realsense camera? OMZ demos use OpenCV to work with media inputs (image or video), which in its turn use system media backends to handle connection with media HW or to do media decoding. Can you work with D435i camera with OpenCV samples?

cc @alvoron @alalek @mshabunin

**Comment by andrei-kochin** [comment]
@xiuxiusen is this issue still actual for you?
