### ISSUE TITLE
Multi ncs2 wont work on facerecognition_demo.py

### ISSUE THREAD

**Issue by glennford49** [openvinotoolkit/open_model_zoo#3481]
I have tested a single ncs2 on facerecognition.py demo, and also tested two ncs2 on same facerecognition.py demo, both yield the same FPS output? Is there any way to speed up the fps value when using 2 ncs2 sticks? 
Tested the multi plugin MULTI:MYRIAD.xx,MYRIAD.xx, but still doesnt work

**Comment by Wovchena** [comment]
MULTI may speed up the execution, but only in some cases
1. MULTI won't help for `-d_fd` because there's only one image to process at a time.
2. MULTI helps for `-d_lm` and `-d_reid` only if there are enough faces detected on an image. Each MYRIAD stick is able to process two inference request at a time. So when you add another stick, you need to have at least three faces detected to generate enough data for landmarks and reid models to start utilizing the second stick.
