### ISSUE TITLE
build text_detection_demo error

### ISSUE THREAD

**Issue by gino0717** [openvinotoolkit/open_model_zoo#3557]
when I build the text_detection_demo file, 
the gcc report following error log: (cmake version : 3.23.1 , gcc version : 10.3.0)

> [100%] Linking CXX executable ../../intel64/Release/text_detection_demo
> CMakeFiles/text_detection_demo.dir/main.cpp.o: In function `main':
> main.cpp:(.text.startup+0x1420): multiple definition of `main'
> CMakeFiles/text_detection_demo.dir/build/CMakeFiles/3.23.1/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text.startup+0x0): first defined here
> collect2: error: ld returned 1 exit status
> text_detection_demo/cpp/CMakeFiles/text_detection_demo.dir/build.make:171: recipe for target 'intel64/Release/text_detection_demo' failed
> make[3]: *** [intel64/Release/text_detection_demo] Error 1
> CMakeFiles/Makefile2:1462: recipe for target 'text_detection_demo/cpp/CMakeFiles/text_detection_demo.dir/all' failed
> make[2]: *** [text_detection_demo/cpp/CMakeFiles/text_detection_demo.dir/all] Error 2
> CMakeFiles/Makefile2:1469: recipe for target 'text_detection_demo/cpp/CMakeFiles/text_detection_demo.dir/rule' failed
> make[1]: *** [text_detection_demo/cpp/CMakeFiles/text_detection_demo.dir/rule] Error 2
> Makefile:495: recipe for target 'text_detection_demo' failed
> make: *** [text_detection_demo] Error 2

It seems that there would appear a file called "CMakeCXXCompilerId.cpp" and it contains a main() function, so the compiling would fail.

I remove the main() function in the "CMakeCXXCompilerId.cpp" then the compiling would work fine ( at least "looks" fine ) . Not sure what would happen when run the demo program.

**Comment by Wovchena** [comment]
For now I only have naïve advice. Try removing all build artifacts and compiling demos from scratch.

**Comment by saurabhmj11** [comment]
The error you are facing indicates that there are multiple definitions of the main() function in your code. This is usually caused by having multiple files with a main() function that are being linked together. However, in this case, it seems that the problem is being caused by the CMakeCXXCompilerId.cpp file which is generated by CMake to identify the compiler being used.

To resolve this issue, you can try the following steps:

Delete the CMakeCXXCompilerId.cpp file in the build directory.
Re-run the CMake configuration step to regenerate the CMakeCXXCompilerId.cpp file.
Build the project again.
Here are the steps in detail:

Navigate to your build directory where the CMakeCXXCompilerId.cpp file is located.
Delete the CMakeCXXCompilerId.cpp file.
Run CMake to regenerate the CMakeCXXCompilerId.cpp file by running the following command:
bash
Copy code
cmake /path/to/text_detection_demo/cpp
Note: Make sure to replace /path/to/text_detection_demo/cpp with the path to the directory containing the CMakeLists.txt file for the text_detection_demo.

After CMake has generated the CMakeCXXCompilerId.cpp file, run the make command to build the project:
go
Copy code
make -j4
Note: You can adjust the -j flag to specify the number of threads to use during the build process.

If you continue to experience issues, please provide more information about your system, the version of OpenCV you are using, and any other relevant details that may help diagnose the problem.
