### ISSUE TITLE
image_processing_demo cpp on win10 [ ERROR ] OpenCV(4.7.0-dev) C:\GHA-OCV-2\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\highgui\src\window_w32.cpp:565: error: (-27:Null pointer) NULL window: 'Image Processing Demo - Super Resolution (press A for help)' in function 'cvGetModeWindow_W32'

### ISSUE THREAD

**Issue by KiwiHana** [openvinotoolkit/open_model_zoo#3714]
OS: win10
openvino 2022.3 achives

C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\image_processing_demo -i image_processing_street_640x360.png -m intel/single-image-super-resolution-1033/FP16/single-image-super-resolution-1033.xml -at sr -o res.png
[ INFO ] OpenVINO
[ INFO ]        version: 2022.3.0
[ INFO ]        build: 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] Reading model intel/single-image-super-resolution-1033/FP16/single-image-super-resolution-1033.xml
[ INFO ] Model name: torch-jit-export
[ INFO ]        Inputs:
[ INFO ]                0, f32, [1,3,360,640], [N,C,H,W]
[ INFO ]                1, f32, [1,3,1080,1920], [N,C,H,W]
[ INFO ]        Outputs:
[ INFO ]                90, f32, [1,3,1080,1920], [...]
[ INFO ] The model intel/single-image-super-resolution-1033/FP16/single-image-super-resolution-1033.xml is loaded to CPU
[ INFO ]        Device: CPU
[ INFO ]                Number of streams: 4
[ INFO ]                Number of threads: 16
[ INFO ]        Number of inference requests: 5
[ ERROR ] OpenCV(4.7.0-dev) C:\GHA-OCV-2\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\highgui\src\window_w32.cpp:565: error: (-27:Null pointer) NULL window: 'Image Processing Demo - Super Resolution (press A for help)' in function 'cvGetModeWindow_W32'

**Comment by saurabhmj11** [comment]
he error message you're seeing is related to the graphical user interface (GUI) of the image_processing_demo in OpenCV. It seems that the window failed to open, which caused the program to crash.

One possible solution to this issue is to try running the demo without the GUI. You can do this by specifying the -no_show flag when running the program. This will disable the GUI and allow the program to run in the command line. Here's an example command:


Copy code
C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\image_processing_demo -i image_processing_street_640x360.png -m intel/single-image-super-resolution-1033/FP16/single-image-super-resolution-1033.xml -at sr -o res.png -no_show
This should prevent the error message you're seeing and allow the program to run successfully.

**Comment by andrei-kochin** [comment]
@KiwiHana  please try suggested approach and feel free to re-open
