### ISSUE TITLE
Crossroad demo does not fully process video

### ISSUE THREAD

**Issue by ashnair1** [openvinotoolkit/open_model_zoo#3961]
Having followed the instructions provided, I have been able to setup the Crossroad C++ demo. Though while running inference on videos I've noticed that the demo does not fully process the videos. 

For example, running inference on a 1 min long video results in an output video containing only 20 sec. For some reason, the remaining 40 seconds of the video was not processed. Not really sure why it stops early and would like some pointers as to why this seems to be the case.

**Comment by Wovchena** [comment]
Can you share to command you used to run the demo?

**Comment by ashnair1** [comment]
Command used:

```
./crossroad_camera_demo -no_show -i /home/ashwin/Downloads/lourve_paris_tour.mp4 -m /media/ashwin/DATA2/open_model_zoo/models/crossroad/intel/person-vehicle-bike-detection-crossroad-0078/FP16/person-vehicle-bike-detection-crossroad-0078.xml -m_reid /media/ashwin/DATA2/open_model_zoo/models/crossroad/intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml -d GPU -o /home/ashwin/Downloads/output_lourve_paris_tour.mp4
```

**Comment by Wovchena** [comment]
If the video is sped up, it can be caused by OpenCV extracting FPS incorrectly: https://github.com/openvinotoolkit/open_model_zoo/blob/a14ddee21bd2ecb85e1ee3f89ce17dbf1dc9343f/demos/common/cpp/utils/src/images_capture.cpp#L181
If the video is truncated, it may be caused by `-limit "<num>"               Optional. Number of frames to store in output. If 0 is set, all frames are stored.` having non zero default value. It may also be that the processing algorithm is incorrect. You are on your own in that situation, alternatively you can compare the result with a different demo to exclude algo problem.

**Comment by ashnair1** [comment]
The truncation was indeed caused by the `-limit` parameter. I had assumed its default value was 0. Setting `-limit 0` fully processes the video as expected.
